source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.2"

gem "httparty", "~> 0.13.7"
gem "puma", "~> 5.0"
gem "rack-cors"
gem "rails", "~> 6.1.3", ">= 6.1.3.2"

group :development, :test do
  gem "pry"
  gem "pry-nav"
end

group :test do
  gem "cucumber-rails", require: false
  gem "guard-rspec"
  gem "rspec-collection_matchers"
  gem "rspec-mocks"
  gem "rspec-rails", "~> 5.0.0"
  gem "rspec-retry"
  gem "simplecov", "0.16", :require => false
  gem "webmock"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
